name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 10 */6 * *' # Tous les 6 jours à 10h UTC
  workflow_dispatch:       # Permet aussi de le lancer manuellement

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase REST API
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/rest/v1/?limit=1"
